---

- name: Instalando o Jenkins
  hosts: automation
  tasks:
  - name: instalando deps
    yum:
     name: "{{ item }}"
    with_items:
      - wget
      - git
      - java

  - name: Instalando repo
    command: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo"

  - name: Instalando key
    command: "rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key"

  - name: Instalando jenkins
    yum:
     name: jenkins
